[26-04-2025 12:43:34] INFO - üîê Authenticating...
[26-04-2025 12:43:34] INFO - [AuthError] Login failed: 404 - <!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <title>Page not found at /api/login/</title>
  <meta name="robots" content="NONE,NOARCHIVE">
  <style>
    html * { padding:0; margin:0; }
    body * { padding:10px 20px; }
    body * * { padding:0; }
    body { font-family: sans-serif; background:#eee; color:#000; }
    body > :where(header, main, footer) { border-bottom:1px solid #ddd; }
    h1 { font-weight:normal; margin-bottom:.4em; }
    h1 small { font-size:60%; color:#666; font-weight:normal; }
    table { border:none; border-collapse: collapse; width:100%; }
    td, th { vertical-align:top; padding:2px 3px; }
    th { width:12em; text-align:right; color:#666; padding-right:.5em; }
    #info { background:#f6f6f6; }
    #info ol { margin: 0.5em 4em; }
    #info ol li { font-family: monospace; }
    #summary { background: #ffc; }
    #explanation { background:#eee; border-bottom: 0px none; }
    pre.exception_value { font-family: sans-serif; color: #575757; font-size: 1.5em; margin: 10px 0 10px 0; }
  </style>
</head>
<body>
  <header id="summary">
    <h1>Page not found <small>(404)</small></h1>
    
    <table class="meta">
      <tr>
        <th scope="row">Request Method:</th>
        <td>POST</td>
      </tr>
      <tr>
        <th scope="row">Request URL:</th>
        <td>http://192.168.211.28:8000/api/login/</td>
      </tr>
      
    </table>
  </header>

  <main id="info">
    
      <p>
      Using the URLconf defined in <code>uploadTesting.urls</code>,
      Django tried these URL patterns, in this order:
      </p>
      <ol>
        
          <li>
            
              <code>
                admin/
                
              </code>
            
          </li>
        
          <li>
            
              <code>
                
                
              </code>
            
              <code>
                api/autoupdate/
                [name='check_update']
              </code>
            
          </li>
        
          <li>
            
              <code>
                
                
              </code>
            
              <code>
                api/download-update/
                [name='download_update']
              </code>
            
          </li>
        
          <li>
            
              <code>
                ^media/(?P&lt;path&gt;.*)$
                
              </code>
            
          </li>
        
      </ol>
      <p>
        
          The current path, <code>api/login/</code>,
        
        didn‚Äôt match any of these.
      </p>
    
  </main>

  <footer id="explanation">
    <p>
      You‚Äôre seeing this error because you have <code>DEBUG = True</code> in
      your Django settings file. Change that to <code>False</code>, and Django
      will display a standard 404 page.
    </p>
  </footer>
</body>
</html>

[26-04-2025 12:44:46] INFO - üîê Authenticating...
[26-04-2025 12:44:46] INFO - üü¢ Screenshot loop started.
[26-04-2025 12:44:46] INFO - üñºÔ∏è Screenshot captured and added to JSON queue: 26-04-2025_12-44-46
[26-04-2025 12:44:46] INFO - üì§ Preparing to send queued screenshot data...
[26-04-2025 12:44:46] INFO - ‚úÖ All screenshot data sent successfully and cleared.
[26-04-2025 12:44:46] INFO - üßπ Cleared error_log.json after successful transmission.
